name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Validar imports (API)
      - name: Test API import
        env:
          SECRET_KEY: "default_ci_secret"
          MODEL_SOURCE: "none"
          MLFLOW_URI: "https://nondomestically-supermundane-fredia.ngrok-free.dev"
        run: |
          python -c "from app.main import app"

      # 5. Validar modelo
      - name: Test model loading
        run: |
          python -c "from app.services.model_service import model_service"

      # 6. Lint básico (no rompe el pipeline)
      - name: Lint code
        run: |
          pip install flake8
          flake8 app src || true